// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using alhadaProject.Models;

#nullable disable

namespace alhadaproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("alhadaProject.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Archeive")
                        .HasColumnType("bit");

                    b.Property<bool>("Buy")
                        .HasColumnType("bit");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<string>("Interest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobile")
                        .HasColumnType("int");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("alhadaProject.Models.ClientDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientNo")
                        .HasColumnType("int");

                    b.Property<string>("CommDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Srl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitorDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitorTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClientDetails");
                });

            modelBuilder.Entity("alhadaProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("alhadaproject.Models.Inbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inboxes");
                });

            modelBuilder.Entity("alhadaProject.Models.Land", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BasinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BasinNo")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<string>("LandDir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LandNo")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNo")
                        .HasColumnType("int");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Lands");
                });

            modelBuilder.Entity("alhadaProject.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApartNo")
                        .HasColumnType("int");

                    b.Property<int>("BalconyNo")
                        .HasColumnType("int");

                    b.Property<int>("BuildYear")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ceramic")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Conditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("DoubleGlass")
                        .HasColumnType("bit");

                    b.Property<bool>("ElectricBlind")
                        .HasColumnType("bit");

                    b.Property<bool>("Elevator")
                        .HasColumnType("bit");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<bool>("Entrance")
                        .HasColumnType("bit");

                    b.Property<bool>("EstablishHeat")
                        .HasColumnType("bit");

                    b.Property<bool>("FirePlace")
                        .HasColumnType("bit");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Furnished")
                        .HasColumnType("bit");

                    b.Property<bool>("Garage")
                        .HasColumnType("bit");

                    b.Property<bool>("Garden")
                        .HasColumnType("bit");

                    b.Property<double>("GardenArea")
                        .HasColumnType("float");

                    b.Property<bool>("Geezer")
                        .HasColumnType("bit");

                    b.Property<string>("GradMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Guard")
                        .HasColumnType("bit");

                    b.Property<string>("GuardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Haunted")
                        .HasColumnType("bit");

                    b.Property<bool>("Heating")
                        .HasColumnType("bit");

                    b.Property<bool>("HomePage")
                        .HasColumnType("bit");

                    b.Property<bool>("Installment")
                        .HasColumnType("bit");

                    b.Property<bool>("Jacozzi")
                        .HasColumnType("bit");

                    b.Property<int>("KitchNo")
                        .HasColumnType("int");

                    b.Property<double>("LandArea")
                        .HasColumnType("float");

                    b.Property<double>("LandTarasArea")
                        .HasColumnType("float");

                    b.Property<bool>("LaundryRoom")
                        .HasColumnType("bit");

                    b.Property<int>("LiveRoomNo")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaidRoom")
                        .HasColumnType("bit");

                    b.Property<bool>("Marble")
                        .HasColumnType("bit");

                    b.Property<int>("MasterNo")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedDate")
                        .HasColumnType("bit");

                    b.Property<bool>("NeverLive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Parquet")
                        .HasColumnType("bit");

                    b.Property<int>("PathNo")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("PrivateGarage")
                        .HasColumnType("bit");

                    b.Property<string>("PromoNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNo")
                        .HasColumnType("int");

                    b.Property<int>("SaloonNo")
                        .HasColumnType("int");

                    b.Property<bool>("ShowerBox")
                        .HasColumnType("bit");

                    b.Property<bool>("SolarHeater")
                        .HasColumnType("bit");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StateArea")
                        .HasColumnType("float");

                    b.Property<string>("StateStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StateView")
                        .HasColumnType("bit");

                    b.Property<bool>("SwimmingPool")
                        .HasColumnType("bit");

                    b.Property<bool>("Taras")
                        .HasColumnType("bit");

                    b.Property<double>("TarasArea")
                        .HasColumnType("float");

                    b.Property<bool>("Viewed")
                        .HasColumnType("bit");

                    b.Property<string>("stateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trading")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("alhadaProject.Models.StateImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("estateImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StateImages");
                });
#pragma warning restore 612, 618
        }
    }
}
